version: '3'
services:
  clickhouse-server:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./database:/var/lib/clickhouse/
      - ./logs:/var/log/clickhouse-server
      - ./users:/etc/clickhouse-server/users.d/
      - ./entrypoint:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      DMIN_PASSWORD: password
      
