[tool.poetry]
name = "dremio"
version = "0.1.0"
description = ""
authors = ["stephenjera"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pynessie = "^0.65.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
