USE ROLE USERADMIN;

CREATE ROLE dbt_role;

GRANT ROLE dbt_role TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE DATABASE thoughtspot;
CREATE SCHEMA thoughtspot.dev;

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE compute_xs TO ROLE dbt_role;
GRANT USAGE ON DATABASE thoughtspot TO ROLE dbt_role;
GRANT USAGE ON ALL SCHEMAS IN DATABASE thoughtspot TO ROLE dbt_role;
GRANT SELECT ON ALL TABLES IN DATABASE thoughtspot TO ROLE dbt_role;
GRANT SELECT ON ALL VIEWS IN DATABASE thoughtspot TO ROLE dbt_role;
GRANT CREATE SCHEMA ON DATABASE thoughtspot TO ROLE dbt_role;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE thoughtspot TO ROLE dbt_role;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE thoughtspot TO ROLE dbt_role;


