version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db

  mongoku:
    image: huggingface/mongoku
    restart: always
    ports:
      - 3100:3100
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb://root:example@mongo:27017"